### ISSUE TITLE
Decor List obscured on mobile by iOS Safari address bar

### ISSUE THREAD

**Issue by cyanliu** [pixlpirate/pikmin-map#3]
I was browsing the website on my phone iPhone 13 mini, with a slightly larger than default text size and the safari address bar covers up a bit of the decor list.

<img src="https://github.com/user-attachments/assets/6f3a1750-6e9c-427d-93d2-51082d0dd84a" width="400px"/>

I scrolled down, notice how there's no "Decor" title at the top, but the last three decor types: Appliance Store, Curry, and DIY are just completely covered by the address bar. For a website like this, the address bar will not automatically minimize and so if I wanted to minimize the address bar, I'd need to go into my browser menu to do so :[ So I wanted to see if you'd be open to just editing the way the website renders instead.

The quick solution I found was making the div smaller by changing the max height, going from
``` css
.decor-list-container--open {
  max-height: calc(100vh - $btn-size - $gap--small * 3);
}
```
to

``` css
.decor-list-container--open {
  max-height: calc(100vh - $btn-size - $gap--small * 6); 
}
```

This makes the div shorter by an arbitrary, so nothing is obscured by the bottom portion of the page. I did try to do some additional research to see why Safari even renders the website behind the address bar, it seems like it's a pain point for other developers too, but I wanted to hear your thoughts on this problem + approach before going ahead and making a PR

merci d'avance : )
